<?php

namespace ClarionApp\LlmClient\ValueObjects;

use Carbon\CarbonImmutable;
use ClarionApp\LlmClient\Models\ReductionStep;

/**
 * The in-memory result of DegradationGate::evaluate()/forRun()
 * (data-model.md §2). Read-only, constructed only by DegradationGate.
 *
 * `composeDisclosure()` is the one sentence every surface reuses —
 * mirroring EnforcementDecision::composeReason()'s "built once, reused
 * everywhere" discipline (research.md D10) — never null except when
 * `outcome === 'full'`, in which case it is always null regardless of what
 * else the instance happens to carry (defensive: outcome alone gates
 * disclosure, never the presence of a governing step). When more than one
 * lever is set on the governing rung, they are always composed in the same
 * fixed order — substitute model, then withheld tools, then history
 * ratio — so two calls describing the identical decision produce
 * byte-identical prose no matter what order the constructor's named
 * arguments happened to be supplied in.
 */
final readonly class DegradationDecision
{
    public const OUTCOME_FULL = 'full';
    public const OUTCOME_REDUCED = 'reduced';

    /**
     * The synthesized tool_result content for every not-yet-executed call
     * in a batch when one of them names a withheld tool — mirroring
     * ConversationWorkDecision::UNEXECUTED_TOOL_RESULT one axis over
     * (research.md D6).
     */
    public const UNEXECUTED_TOOL_RESULT = 'This tool call was not executed: the requested capability is unavailable in the current reduced operating mode.';

    /**
     * @param  string  $outcome  one of OUTCOME_FULL, OUTCOME_REDUCED
     * @param  ReductionStep|null  $governingStep  the rung that produced the
     *   outcome — null only when `outcome === 'full'`
     * @param  string|null  $axis  the LimitAxis value that selected
     *   $governingStep (research.md D7)
     * @param  string|null  $ratio  the axis's consumption ratio at decision
     *   time, a bcmath-formatted plain-decimal string — never a float
     * @param  string|null  $effectiveModel  $governingStep->substitute_model,
     *   or null meaning "use the conversation's own model"
     * @param  string|null  $effectiveServerId  $governingStep->substitute_server_id
     * @param  list<string>  $withheldTools  empty when the governing step
     *   withholds nothing
     * @param  string|null  $historyBudgetRatio  $governingStep->history_budget_ratio,
     *   a plain-decimal string — never a float
     * @param  CarbonImmutable|null  $resetsAt  the governing axis's own reset
     *   time, reused verbatim from whichever sibling reading supplied the
     *   ratio — never recomputed
     */
    public function __construct(
        public string $outcome,
        public ?ReductionStep $governingStep = null,
        public ?string $axis = null,
        public ?string $ratio = null,
        public ?string $effectiveModel = null,
        public ?string $effectiveServerId = null,
        public array $withheldTools = [],
        public ?string $historyBudgetRatio = null,
        public ?CarbonImmutable $resetsAt = null,
    ) {
    }

    /**
     * The constant "nothing applies" instance — returned by forRun() when
     * no degradation_events row exists for a run id, and by evaluate()
     * whenever the ladder is empty or nothing is crossed.
     */
    public static function full(): self
    {
        return new self(outcome: self::OUTCOME_FULL);
    }

    /**
     * Null on `full` (FR-005: a full-capacity response carries no
     * disclosure at all, not an empty-string one). Otherwise one sentence
     * naming the governing axis, what specifically changed, and when full
     * capacity is expected to return.
     */
    public function composeDisclosure(): ?string
    {
        if ($this->outcome !== self::OUTCOME_REDUCED) {
            return null;
        }

        $levers = [];

        if ($this->effectiveModel !== null) {
            $levers[] = sprintf(
                'responses are being generated by %s instead of the usual model',
                $this->effectiveModel,
            );
        }

        if ($this->withheldTools !== []) {
            $levers[] = sprintf(
                'the following capabilities are unavailable for this response: %s',
                implode(', ', $this->withheldTools),
            );
        }

        if ($this->historyBudgetRatio !== null) {
            $levers[] = sprintf(
                'conversation history is being carried into this response at %s of its usual budget',
                $this->historyBudgetRatio,
            );
        }

        $resets = $this->resetsAt !== null
            ? $this->resetsAt->format('Y-m-d H:i').' UTC'
            : 'the next reset';

        return sprintf(
            'Running in a reduced mode right now because %s is close to its limit: %s. '
            .'Expected to return to full capability around %s.',
            self::axisLabel($this->axis),
            implode('; ', $levers),
            $resets,
        );
    }

    /**
     * The refusal sentence for a mid-response attempt to call a tool this
     * decision withholds (contracts §4, research.md D6) — a distinct fact
     * from composeDisclosure()'s "reduced but still usable" sentence, never
     * reused verbatim: this one always ends the response rather than
     * continuing it.
     */
    public function composeWithheldToolRefusal(): string
    {
        $resets = $this->resetsAt !== null
            ? $this->resetsAt->format('Y-m-d H:i').' UTC'
            : 'the next reset';

        return sprintf(
            'This capability is unavailable in the current reduced operating mode, and the request cannot be '
            .'completed without it, so it has been refused rather than answered without it. Full capability is '
            .'expected back %s.',
            $resets,
        );
    }

    /**
     * The wire shape both the synchronous and streamed completion paths
     * attach as `degradation` (contracts §4) — null on `full`, so a caller
     * can key its own `degraded` flag off whether this returns null.
     */
    public function toDisclosureArray(): ?array
    {
        if ($this->outcome !== self::OUTCOME_REDUCED) {
            return null;
        }

        return [
            'axis' => $this->axis,
            'substitute_model' => $this->effectiveModel,
            'withheld_tools' => $this->withheldTools,
            'history_budget_ratio' => $this->historyBudgetRatio,
            'resets_at' => $this->resetsAt?->toIso8601String(),
        ];
    }

    private static function axisLabel(?string $axis): string
    {
        return match ($axis) {
            LimitAxis::BudgetUser->value => 'your spending',
            LimitAxis::BudgetInstallation->value => "this installation's spending",
            LimitAxis::RateLimit->value => 'your request rate',
            LimitAxis::ConversationWork->value => "this conversation's work",
            default => 'a configured limit',
        };
    }
}
