<?php

namespace ClarionApp\LlmClient\Tests\Feature;

use ClarionApp\Backend\ApiManager;
use ClarionApp\LlmClient\Services\AgentDefinitionParser;
use ClarionApp\LlmClient\Services\AgentDefinitionValidator;
use Dedoc\Scramble\Generator;
use Illuminate\Support\Facades\Artisan;
use Mockery;
use PHPUnit\Framework\Attributes\Test;
use Symfony\Component\Yaml\Yaml;
use Tests\TestCase;

/**
 * End-to-end journey for 089-agent-scaffolding-cli (spec.md US1's own
 * Independent Test, contracts §1, research.md D12). This is the single,
 * ongoing Feature-level journey test file for the whole feature — Phase 4
 * (US3) and Phase 5 (US2) both extend this same file with further
 * scenarios rather than creating new ones (plan.md's own Project
 * Structure names it once, for the whole feature). This Phase 3 pass
 * covers only US1's own generic (no-kind) scope.
 *
 * Written before `agent:create` is registered — expected to fail (command
 * not found / non-zero unexpected exit) until Phase 3's Implementation
 * tasks land. That is the intended RED state, not a mistake.
 */
class AgentScaffoldingJourneyTest extends TestCase
{
    /** @var string[] */
    private array $tempDirs = [];

    protected function tearDown(): void
    {
        foreach ($this->tempDirs as $dir) {
            $this->removeDirectory($dir);
        }
        $this->tempDirs = [];

        $this->clearOperationCatalog();
        Mockery::close();

        parent::tearDown();
    }

    private function makeTempDir(): string
    {
        $dir = sys_get_temp_dir().'/agent_scaffolding_journey_test_'.uniqid('', true);
        mkdir($dir, 0777, true);
        $this->tempDirs[] = $dir;

        return $dir;
    }

    private function removeDirectory(string $path): void
    {
        if (!is_dir($path)) {
            return;
        }

        @chmod($path, 0777);

        foreach (new \FilesystemIterator($path) as $item) {
            if ($item->isDir()) {
                $this->removeDirectory($item->getPathname());
            } else {
                @unlink($item->getPathname());
            }
        }

        @rmdir($path);
    }

    /**
     * @return string[] non-"."/".." entries directly inside $dir
     */
    private function directoryEntries(string $dir): array
    {
        return array_values(array_diff(scandir($dir) ?: [], ['.', '..']));
    }

    /**
     * Every one of the 15 leaf settings quickstart.md step 1 names, each
     * immediately preceded (skipping only blank lines) by a non-empty "#"
     * comment line. Tolerant of either a nested-YAML or a dotted-key
     * rendering choice for the memory, tools, and safety groups — only the
     * leaf key name and its immediate ":" are required, preceded by "."
     * or whitespace.
     */
    private function assertLeafSettingsHaveComments(string $content): void
    {
        $labels = [
            'format_version', 'name', 'version', 'instructions', 'model',
            'scratch', 'short_term', 'long_term', 'episodic', 'declarative',
            'capabilities', 'allow', 'deny', 'confirmation_required', 'denylist',
        ];

        $lines = explode("\n", $content);

        foreach ($labels as $label) {
            $keyLineIndex = null;

            foreach ($lines as $index => $line) {
                if (preg_match('/(^|[.\s])'.preg_quote($label, '/').'\s*:/', $line) === 1) {
                    $keyLineIndex = $index;
                    break;
                }
            }

            $this->assertNotNull($keyLineIndex, "Expected a \"{$label}\" setting line in the generated file.");

            $commentLineIndex = $keyLineIndex - 1;
            while ($commentLineIndex >= 0 && trim($lines[$commentLineIndex]) === '') {
                $commentLineIndex--;
            }

            $this->assertGreaterThanOrEqual(0, $commentLineIndex, "Expected a comment line before \"{$label}\".");

            $commentLine = trim($lines[$commentLineIndex]);
            $this->assertStringStartsWith('#', $commentLine, "Expected \"{$label}\" to be preceded by a comment line.");
            $this->assertGreaterThan(1, strlen($commentLine), "Expected the comment before \"{$label}\" to be non-empty.");
        }
    }

    // ---------------------------------------------------------------
    // A complete, valid, immediately-runnable definition, generated by
    // naming it alone (US1 Independent Test).
    // ---------------------------------------------------------------

    #[Test]
    public function naming_a_new_agent_produces_a_complete_valid_immediately_runnable_definition(): void
    {
        $this->seedOperationCatalog([]);
        $dir = $this->makeTempDir();

        $exitCode = Artisan::call('agent:create', [
            'name' => 'weather-agent',
            '--path' => $dir,
        ]);

        $this->assertSame(0, $exitCode);

        $path = $dir.'/weather-agent.yaml';
        $this->assertFileExists($path);
        $content = file_get_contents($path);

        // Re-validated directly in the test — not merely trusting the
        // command's own internal check (quickstart step 1's own explicit
        // instruction).
        $result = (new AgentDefinitionValidator(new AgentDefinitionParser()))->check($content);
        $this->assertTrue($result->valid);
        $this->assertSame([], $result->problems);

        $parsed = Yaml::parse($content);
        $this->assertIsArray($parsed);

        foreach (['format_version', 'name', 'version', 'instructions', 'model', 'memory', 'capabilities', 'tools', 'safety'] as $key) {
            $this->assertArrayHasKey($key, $parsed, "Expected the generated document to contain a top-level \"{$key}\" key.");
        }

        $this->assertIsArray($parsed['memory']);
        foreach (['scratch', 'short_term', 'long_term', 'episodic', 'declarative'] as $memoryKey) {
            $this->assertArrayHasKey($memoryKey, $parsed['memory']);
        }

        $this->assertIsArray($parsed['tools']);
        $this->assertArrayHasKey('allow', $parsed['tools']);
        $this->assertArrayHasKey('deny', $parsed['tools']);

        $this->assertIsArray($parsed['safety']);
        $this->assertArrayHasKey('confirmation_required', $parsed['safety']);
        $this->assertArrayHasKey('denylist', $parsed['safety']);

        $this->assertLeafSettingsHaveComments($content);
    }

    // ---------------------------------------------------------------
    // Phase 4 (US3) — generation never silently damages or fails
    // invisibly (T021). AgentCreateCommand does not yet catch
    // AgentScaffoldCollisionException/AgentScaffoldDestinationException
    // (that wiring is Phase 4's own Implementation scope, T022) — the
    // first two cases below are expected to fail RED against Phase 3's
    // code: the exception propagates rather than producing the clean
    // exit-1/message behavior asserted here. The last two cases exercise
    // already-built Phase 3 behavior and are expected to pass.
    // ---------------------------------------------------------------

    #[Test]
    public function a_same_name_collision_is_refused_and_the_existing_file_is_untouched(): void
    {
        $this->seedOperationCatalog([]);
        $dir = $this->makeTempDir();

        $firstExitCode = Artisan::call('agent:create', [
            'name' => 'dup',
            '--path' => $dir,
        ]);
        $this->assertSame(0, $firstExitCode);

        $path = $dir.'/dup.yaml';
        $this->assertFileExists($path);
        $originalContent = file_get_contents($path);
        $originalMtime = filemtime($path);

        $secondExitCode = Artisan::call('agent:create', [
            'name' => 'dup',
            '--path' => $dir,
        ]);

        $this->assertSame(1, $secondExitCode, 'A same-name collision must be refused with exit 1.');

        $output = Artisan::output();
        $this->assertStringContainsString('An agent definition already exists at', $output);
        $this->assertStringContainsString($path, $output);

        $this->assertSame(
            $originalContent,
            file_get_contents($path),
            'The pre-existing file\'s content must be byte-for-byte unchanged after the refused attempt.'
        );
        $this->assertSame(
            $originalMtime,
            filemtime($path),
            'The pre-existing file\'s mtime must be unchanged after the refused attempt.'
        );
    }

    #[Test]
    public function an_unwritable_destination_fails_clearly_with_nothing_left_behind(): void
    {
        $this->seedOperationCatalog([]);
        $dir = $this->makeTempDir();

        // (a) --path pointing at a directory that does not exist.
        $missingDir = $dir.'/does-not-exist';

        $exitCodeA = Artisan::call('agent:create', [
            'name' => 'x',
            '--path' => $missingDir,
        ]);

        $this->assertSame(1, $exitCodeA, 'A missing destination directory must be refused with exit 1.');
        $this->assertStringContainsString('Destination directory does not exist:', Artisan::output());
        $this->assertDirectoryDoesNotExist($missingDir);

        // (b) --path pointing at a real temp directory chmod'd to 0500
        // (non-writable). Restore unconditionally, even on assertion
        // failure, so the directory can still be cleaned up in tearDown().
        chmod($dir, 0500);

        try {
            $exitCodeB = Artisan::call('agent:create', [
                'name' => 'x',
                '--path' => $dir,
            ]);

            $this->assertSame(1, $exitCodeB, 'An unwritable destination directory must be refused with exit 1.');
            $this->assertStringContainsString('Destination directory is not writable:', Artisan::output());
        } finally {
            chmod($dir, 0777);
        }

        $this->assertSame(
            [],
            $this->directoryEntries($dir),
            'No file may be created anywhere as a result of either sub-case.'
        );
    }

    #[Test]
    public function a_whitespace_only_name_is_distinguishable_from_a_collision(): void
    {
        $this->seedOperationCatalog([]);
        $dir = $this->makeTempDir();

        $exitCode = Artisan::call('agent:create', [
            'name' => '   ',
            '--path' => $dir,
        ]);

        $this->assertSame(1, $exitCode);

        $output = Artisan::output();
        $this->assertStringContainsString('A definition must state a non-empty "name".', $output);
        $this->assertStringNotContainsString('An agent definition already exists at', $output);
        $this->assertSame([], $this->directoryEntries($dir), 'No file may be written for a refused name.');
    }

    #[Test]
    public function every_generated_result_validates_immediately_via_the_real_cli_path(): void
    {
        $this->seedOperationCatalog([]);
        $dir = $this->makeTempDir();

        $exitCode = Artisan::call('agent:create', [
            'name' => 'validate-me',
            '--path' => $dir,
        ]);

        $this->assertSame(0, $exitCode);

        $path = $dir.'/validate-me.yaml';
        $this->assertFileExists($path);
        $content = file_get_contents($path);

        $validator = $this->app->make(AgentDefinitionValidator::class);
        $result = $validator->check($content);

        $this->assertTrue($result->valid);
        $this->assertSame([], $result->problems);
    }

    // ---------------------------------------------------------------
    // Operation catalog fixture (copied verbatim from
    // AgentDefinitionMinimalJourneyTest.php's own established pattern)
    // ---------------------------------------------------------------

    /**
     * @param array<string, array{path: string, method: string, summary: string}> $operations
     */
    private function seedOperationCatalog(array $operations): void
    {
        $paths = [];
        foreach ($operations as $operationId => $entry) {
            $paths[$entry['path']][$entry['method']] = [
                'operationId' => $operationId,
                'summary' => $entry['summary'],
            ];
        }
        $doc = ['paths' => $paths];

        $prop = (new \ReflectionClass(ApiManager::class))->getProperty('apiDocsCache');
        $prop->setAccessible(true);
        $prop->setValue(null, $doc);

        $generator = Mockery::mock(Generator::class);
        $generator->shouldReceive('__invoke')->andReturn($doc);
        $this->app->instance(Generator::class, $generator);
    }

    private function clearOperationCatalog(): void
    {
        $prop = (new \ReflectionClass(ApiManager::class))->getProperty('apiDocsCache');
        $prop->setAccessible(true);
        $prop->setValue(null, null);
    }
}
